import type { Product } from "./types";

const REFUND = { q: "What if it is not right for me?", a: "Email us and we will sort it out in plain terms. Refund terms are in our terms page and are confirmed in writing before you pay." };

export const PRODUCTS: Product[] = [
  {
    slug: "dmarc-setup-guide",
    kind: "guide",
    name: "DMARC and SPF Setup Guide for Small Business",
    bluf: "A plain-English walk through making your email domain hard to fake, in the order that keeps your real email flowing.",
    forWho: ["Owners whose email goes to spam or whose name has been faked", "Whoever looks after IT for a small team, even part time", "Businesses asked by a client or insurer about email security"],
    youGet: ["Step-by-step DNS changes for SPF, DKIM and DMARC", "A safe rollout order: monitor first, then quarantine, then reject", "A checklist for each common mail provider", "A one-page summary to hand to your IT provider"],
    delivery: { file: "dmarc-setup-guide.pdf", format: "PDF, about 20 pages", note: "Built from the same method our free SpoofGuard check uses on public DNS records." },
    suggestedPriceAud: 49,
    faq: [{ q: "Do I need to be technical?", a: "No. Each step says what to change, where, and how to check it worked." }, REFUND],
  },
  {
    slug: "spoofguard-self-check-checklist",
    kind: "checklist",
    name: "Email Spoofing Self-Check Checklist",
    bluf: "Ten checks you can run in an afternoon, using public records only, to see whether someone could send email as your business.",
    forWho: ["Owners who want a quick answer before paying anyone", "Bookkeepers and office managers", "Anyone preparing for a customer security questionnaire"],
    youGet: ["Ten checks with what a good and a bad result looks like", "Where to look each one up, free", "A scoring sheet so you can repeat the check later", "What to do first when a check fails"],
    delivery: { file: "spoofguard-self-check-checklist.pdf", format: "PDF, 4 pages", note: "Public records only. Nothing is scanned, touched or logged in." },
    suggestedPriceAud: 15,
    faq: [{ q: "Is there a free version?", a: "Yes. Our free scan at titanos.tech/scan checks your domain for you. This checklist teaches you to do it yourself." }, REFUND],
  },
  {
    slug: "essential-eight-ml1-checklist",
    kind: "checklist",
    name: "Essential Eight Maturity Level One Checklist",
    bluf: "The eight mitigation strategies as a plain checklist a small business can work through, with the evidence to keep for each.",
    forWho: ["Suppliers asked for Essential Eight evidence on a tender or contract", "IT providers who support small teams", "Owners who want to know where they stand"],
    youGet: ["One page per strategy with the maturity level one target", "What evidence to collect and where to store it", "A gap sheet you can hand to your IT provider", "A short glossary in everyday words"],
    delivery: { file: "essential-eight-ml1-checklist.pdf", format: "PDF, about 14 pages", note: "General information, not legal or audit advice. Check against the current official guidance." },
    suggestedPriceAud: 30,
    faq: [{ q: "Does this certify us?", a: "No. It helps you prepare and gather evidence. It is not an assessment." }, REFUND],
  },
  {
    slug: "privacy-policy-template-pack",
    kind: "template",
    name: "Privacy Policy Template Pack",
    bluf: "A fill-in-the-blanks privacy policy and collection notice set for a small Australian business, written in everyday words.",
    forWho: ["Small businesses with no privacy policy yet", "Owners whose current policy was copied from somewhere else", "Businesses preparing for a larger client's due diligence"],
    youGet: ["A privacy policy template with guidance in the margins", "A collection notice for forms and quotes", "A short staff handout", "A review checklist to run once a year"],
    delivery: { file: "privacy-policy-template-pack.docx", format: "Word documents, 4 files", note: "General information, not legal advice. Have a lawyer review it if your situation is complex." },
    suggestedPriceAud: 30,
    faq: [{ q: "Is this legal advice?", a: "No. It is a starting template. Have a lawyer review it if your situation is complex." }, REFUND],
  },
  {
    slug: "privacy-adm-wording-guide",
    kind: "guide",
    name: "Privacy Wording for Automated Decisions",
    bluf: "How to describe, in your privacy policy, where software helps make decisions about people, so the wording is clear and honest.",
    forWho: ["Businesses using automated tools for quotes, screening or scheduling", "Owners adding AI tools and unsure what to disclose", "Advisers who review privacy policies"],
    youGet: ["A short explanation of what counts and what does not", "Sample wording you can adapt", "A list of questions to ask each tool vendor", "A before and after example"],
    delivery: { file: "privacy-adm-wording-guide.pdf", format: "PDF, about 8 pages", note: "General information, not legal advice." },
    offerSlug: "privacy-adm-wording-check",
    suggestedPriceAud: 29,
    faq: [REFUND],
  },
  {
    slug: "five-jurisdiction-privacy-bundle",
    kind: "template",
    name: "Five-Jurisdiction Privacy Bundle",
    bluf: "Privacy policy starting points for businesses that serve customers in more than one country, with the main differences set out side by side.",
    forWho: ["Exporters and online sellers", "Businesses with customers overseas", "Advisers who write privacy policies for small clients"],
    youGet: ["A starting template per jurisdiction", "A side-by-side table of the main differences", "A checklist of where each rule applies", "Plain notes on what to confirm with a lawyer"],
    delivery: { file: "five-jurisdiction-privacy-bundle.zip", format: "ZIP of Word and PDF files", note: "General information, not legal advice. Laws change, so check the current rules for each place." },
    offerSlug: "five-jurisdiction-privacy-bundle",
    suggestedPriceAud: 49,
    faq: [REFUND],
  },
  {
    slug: "breach-response-runbook",
    kind: "template",
    name: "Data Breach Response Runbook",
    bluf: "A calm, step-by-step plan for the first 72 hours after something goes wrong, written so a small team can follow it under stress.",
    forWho: ["Owners who would not know who to call first", "Businesses asked for an incident plan by a client or insurer", "Office managers who end up in charge when things break"],
    youGet: ["A one-page first-hour sheet", "Roles and a contact list to fill in", "A decision guide for whether notification is needed", "Message templates for staff and customers", "A review form for after the event"],
    delivery: { file: "breach-response-runbook.docx", format: "Word document, about 12 pages", note: "General information, not legal advice." },
    suggestedPriceAud: 30,
    faq: [REFUND],
  },
  {
    slug: "vendor-risk-register-template",
    kind: "template",
    name: "Vendor Risk Register Template",
    bluf: "A simple spreadsheet to list every supplier that touches your data, what they hold, and what you checked.",
    forWho: ["Businesses answering supplier questionnaires from larger clients", "Owners who use many software tools", "Bookkeepers and operations managers"],
    youGet: ["A ready-to-use register with example rows", "A short risk rating guide", "A review calendar", "A one-page instructions sheet"],
    delivery: { file: "vendor-risk-register-template.xlsx", format: "Spreadsheet", note: "Works in Excel and Google Sheets." },
    suggestedPriceAud: 15,
    faq: [REFUND],
  },
  {
    slug: "customer-dossier-method-guide",
    kind: "guide",
    name: "The Customer Dossier Method",
    bluf: "How we research one organisation from public records and turn it into a short, useful brief, written so you can run it on your own prospects.",
    forWho: ["Sales owners who want to walk into a first call prepared", "Bid writers and consultants", "Advisers who want a repeatable research habit"],
    youGet: ["The method in order, from first search to finished brief", "Which public sources to use and what each tells you", "A one-page brief template", "How to record sources so every claim can be checked", "Two worked layouts with the names removed"],
    delivery: { file: "customer-dossier-method-guide.pdf", format: "PDF, about 24 pages, plus a template file", note: "Public records only. The guide covers the limits of what to claim from them." },
    suggestedPriceAud: 100,
    faq: [REFUND],
  },
  {
    slug: "quote-follow-up-playbook",
    kind: "playbook",
    name: "Quote Follow-Up Playbook for Tradies",
    bluf: "How to chase quotes politely and on time, with the messages ready to copy, so fewer quotes go quiet.",
    forWho: ["Tradies who send quotes and then hear nothing", "Small trade businesses with an office person part time", "Owners who want an AI tool to draft the follow-ups"],
    youGet: ["A simple follow-up rhythm", "Message templates for text and email", "A tracking sheet", "How to set an AI assistant up to draft messages for you to approve"],
    delivery: { file: "quote-follow-up-playbook.pdf", format: "PDF, about 12 pages, plus a tracking sheet", note: "You stay in control: nothing here sends a message without you." },
    suggestedPriceAud: 30,
    faq: [REFUND],
  },
  {
    slug: "invoice-chasing-playbook",
    kind: "playbook",
    name: "Invoice Chasing Playbook for Small Business",
    bluf: "A calm, three-step way to get paid on time without damaging the relationship, with every message written out.",
    forWho: ["Owners who dread chasing late payers", "Bookkeepers who send the reminders", "Trades and services with 14 and 30 day terms"],
    youGet: ["A reminder schedule from friendly to firm", "Message templates for each step", "Wording for payment plans", "A sheet to track who has been chased and when"],
    delivery: { file: "invoice-chasing-playbook.pdf", format: "PDF, about 10 pages, plus a tracking sheet", note: "Terms and remedies depend on your contracts. Check yours first." },
    suggestedPriceAud: 30,
    faq: [REFUND],
  },
  {
    slug: "efficiency-proof-pack",
    kind: "guide",
    name: "The Efficiency Proof Pack: Measure Hours Given Back",
    bluf: "How to measure what an AI or automation change really saves, with before and after sheets, so you can prove it to yourself and your team.",
    forWho: ["Owners trying AI tools and unsure if they help", "Managers who need to show a result", "Advisers who sell automation and want honest numbers"],
    youGet: ["A before and after measurement method", "A time log sheet and a results sheet", "A rule for what counts as a saving and what does not", "A one-page report layout"],
    delivery: { file: "efficiency-proof-pack.pdf", format: "PDF plus two spreadsheets", note: "The method we use on our own work: measure first, claim second." },
    suggestedPriceAud: 100,
    faq: [REFUND],
  },
  {
    slug: "course-ai-for-tradies",
    kind: "course",
    name: "Course: AI for Tradies, Start to Finish",
    bluf: "A short course that takes a trade business from no AI to a working quote, follow-up and invoice routine, with you approving every message.",
    forWho: ["Tradies and trade business owners", "Small teams with part-time office help", "Anyone who wants a practical start without the jargon"],
    youGet: ["Four modules and twelve short lessons", "Every template, message and sheet used in the lessons", "A checklist to measure your own before and after", "Lifetime access to the files as delivered"],
    delivery: { file: "course-ai-for-tradies.zip", format: "ZIP: lesson notes (PDF), templates, sheets", note: "Delivered as a download bundle. Video is not part of version one." },
    suggestedPriceAud: 100,
    outline: [
      { title: "Module 1: Where your hours go", lessons: [
        { title: "Log one week of admin", outcome: "You know which jobs eat the most time." },
        { title: "Pick the first job to hand over", outcome: "One clear job with a clear finish line." },
        { title: "Set the rules: you approve everything", outcome: "A written rule for what AI may and may not do." } ] },
      { title: "Module 2: Quotes", lessons: [
        { title: "Job notes to a first-draft quote", outcome: "A repeatable way to draft quotes faster." },
        { title: "Quote follow-up rhythm", outcome: "A schedule and messages you approve." },
        { title: "Keeping your tone", outcome: "Drafts that sound like you." } ] },
      { title: "Module 3: Getting paid", lessons: [
        { title: "Invoice reminders that keep the relationship", outcome: "Three-step reminder set." },
        { title: "Payment plan wording", outcome: "Plain wording for slow payers." },
        { title: "Tracking who owes what", outcome: "One sheet you update in minutes." } ] },
      { title: "Module 4: Prove it", lessons: [
        { title: "Measure before and after", outcome: "Your own numbers, not ours." },
        { title: "Privacy and safety basics", outcome: "What not to paste into any AI tool." },
        { title: "Your next step", outcome: "A plan for the next job to hand over." } ] },
    ],
    bundle: ["Lesson notes, 12 PDFs", "Quote follow-up message pack", "Invoice reminder message pack", "Time log and results sheets", "Privacy and safety one-pager", "Course completion checklist"],
    faq: [{ q: "Do I need any software?", a: "A free or paid AI assistant of your choice. The lessons say what to look for." }, REFUND],
  },
  {
    slug: "course-email-security-for-owners",
    kind: "course",
    name: "Course: Email Security for Business Owners",
    bluf: "A short course that takes you from not knowing your email posture to a locked-down domain, a tested incident plan and evidence for clients.",
    forWho: ["Owners and managers of small businesses", "Part-time IT and office staff", "Suppliers asked to show their security evidence"],
    youGet: ["Four modules and ten short lessons", "The DMARC guide, checklists and runbook as part of the bundle", "A one-page evidence summary for clients", "Lifetime access to the files as delivered"],
    delivery: { file: "course-email-security-for-owners.zip", format: "ZIP: lesson notes (PDF), guides, templates, sheets", note: "Delivered as a download bundle. Video is not part of version one." },
    suggestedPriceAud: 100,
    outline: [
      { title: "Module 1: See your own posture", lessons: [
        { title: "How email faking works, in plain words", outcome: "You can explain the risk to your team." },
        { title: "Run the ten-point self-check", outcome: "A scored baseline for your domain." } ] },
      { title: "Module 2: Lock the domain", lessons: [
        { title: "SPF and DKIM without tears", outcome: "Both set up and checked." },
        { title: "DMARC: monitor, quarantine, reject", outcome: "A safe rollout plan for your mail." },
        { title: "Test and keep it healthy", outcome: "A monthly five-minute check." } ] },
      { title: "Module 3: Be ready", lessons: [
        { title: "The first 72 hours after a problem", outcome: "A runbook with names filled in." },
        { title: "Your supplier list", outcome: "A vendor register started." },
        { title: "Essential Eight at maturity level one", outcome: "A gap sheet for your IT provider." } ] },
      { title: "Module 4: Show your work", lessons: [
        { title: "Build a one-page evidence summary", outcome: "Something you can send a client or insurer." },
        { title: "What to do next", outcome: "A priority list for the next quarter." } ] },
    ],
    bundle: ["Lesson notes, 10 PDFs", "DMARC and SPF setup guide", "Email spoofing self-check checklist", "Data breach response runbook", "Vendor risk register template", "Essential Eight level one checklist", "Evidence summary template"],
    faq: [{ q: "Can my IT provider use this too?", a: "Yes. The guides are written so you and your IT provider can work from the same pages." }, REFUND],
  },
];
