import { SIGIL_NAMES } from "../lib/sigilSet";

/**
 * SIGILS EVERYWHERE, MEANINGS NOWHERE. A sigil is a glyph plus at most a neutral
 * codename. Nothing here (or anywhere on the site) says what a sigil means.
 * Glyphs are phi geometry, generated by scripts/gen_sigils.mjs, tinted via CSS mask.
 */
const PHI = 1.618;
const at = (i: number) => SIGIL_NAMES[((i % SIGIL_NAMES.length) + SIGIL_NAMES.length) % SIGIL_NAMES.length];

export function Sigil({
  index = 0,
  size = 26,
  tone = "var(--gold)",
  codename = false,
  egg = false,
  className = "",
}: {
  index?: number;
  size?: number;
  tone?: string;
  codename?: boolean;
  egg?: boolean;
  className?: string;
}) {
  const name = at(index);
  const url = `/sigils/${name.toLowerCase()}.svg`;
  return (
    <span
      className={`sigil ${egg ? "sigil-egg" : ""} ${className}`}
      title={egg ? name : undefined}
      aria-hidden="true"
      style={{ display: "inline-flex", alignItems: "center", gap: 8, verticalAlign: "middle" }}
    >
      <span
        className="sigil-glyph"
        style={{
          width: size,
          height: size,
          background: tone,
          WebkitMaskImage: `url(${url})`,
          maskImage: `url(${url})`,
          WebkitMaskSize: "contain",
          maskSize: "contain",
          WebkitMaskRepeat: "no-repeat",
          maskRepeat: "no-repeat",
          display: "inline-block",
        }}
      />
      {codename && (
        <span style={{ fontSize: 12, letterSpacing: "0.22em", textTransform: "uppercase", opacity: 0.7 }}>{name}</span>
      )}
    </span>
  );
}

/** Section mark: sits above a heading. */
export function SigilMark({ index = 0 }: { index?: number }) {
  return (
    <div aria-hidden="true" style={{ textAlign: "center", marginBottom: 10, opacity: 0.85 }}>
      <Sigil index={index} size={Math.round(16 * PHI * PHI)} egg />
    </div>
  );
}

/** Card corner seal: absolutely positioned, parent needs position: relative. */
export function SigilCorner({ index = 0 }: { index?: number }) {
  return (
    <span aria-hidden="true" style={{ position: "absolute", top: 10, right: 10, opacity: 0.5, pointerEvents: "none" }}>
      <Sigil index={index} size={22} />
    </span>
  );
}

/** Footer seal row: every glyph in the set, codenames on hover only. */
export function SigilSeals() {
  return (
    <div
      aria-hidden="true"
      style={{ display: "flex", flexWrap: "wrap", justifyContent: "center", gap: 14, padding: "26px 16px 6px", opacity: 0.55 }}
    >
      {SIGIL_NAMES.map((_, i) => (
        <Sigil key={i} index={i} size={26} egg />
      ))}
    </div>
  );
}

/** Background constellation: golden-angle scatter of faint glyphs, fixed, behind content. */
export function SigilConstellation({ count = 13 }: { count?: number }) {
  const GA = 137.50776;
  return (
    <div
      aria-hidden="true"
      style={{ position: "fixed", inset: 0, zIndex: 0, pointerEvents: "none", overflow: "hidden", opacity: 0.07 }}
    >
      {Array.from({ length: count }).map((_, i) => {
        const x = (i * GA * 0.618) % 100;
        const y = ((i + 1) * 100 * 0.618 * 0.618 * 1.0 + i * 13) % 100;
        const s = 40 + ((i * 29) % 90);
        return (
          <span key={i} style={{ position: "absolute", left: `${x}%`, top: `${y}%`, transform: `rotate(${(i * GA) % 360}deg)` }}>
            <Sigil index={i * 3 + 1} size={s} tone="var(--ice, #9fc7ff)" />
          </span>
        );
      })}
    </div>
  );
}

/** Loader: the glyph turns by phi steps. Reduced motion shows it still (see globals.css). */
export function SigilLoader({ index = 5 }: { index?: number }) {
  return (
    <div role="status" aria-label="Loading" style={{ display: "grid", placeItems: "center", minHeight: "40vh" }}>
      <span className="sigil-spin">
        <Sigil index={index} size={68} />
      </span>
    </div>
  );
}
