// GENERATED by scripts/gen_sigils.mjs. Glyph codenames only; no meanings.
export const SIGIL_NAMES = ["Zephyr","Paragon","Helix","Fathom","Quasar","Tessel","Cinder","Echo","Dusk","Orrery","Stygian","Ingot","Vesper","Pallas","Borealis","Cipher","Gossamer","Talon","Eidolon","Solace","Verge","Nimbus","Rune","Sylph","Meridian","Harbor","Wraith","Iris","Corvid","Mirage","Kestrel","Flint","Vantage","Lumen","Umbra","Juno","Ostra","Riven"] as const;
export type SigilName = (typeof SIGIL_NAMES)[number];
