// W2: real deep-space imagery, licences in scripts/images/manifest.json (single source for the credits page).
// Responsive files are generated by scripts/images/build_images.mjs into public/space/.
import manifest from "../scripts/images/manifest.json";
import generated from "./space-images.generated.json";

export type SpaceFile = { w: number; h: number; fmt: "avif" | "webp"; bytes: number; name: string };
export type SpaceImageMeta = (typeof manifest)[number] & { width: number; height: number; files: SpaceFile[] };

const byId = new Map(generated.map((g) => [g.id, g as { id: string; width: number; height: number; files: SpaceFile[] }]));

export const SPACE_IMAGES: SpaceImageMeta[] = manifest.map((m) => {
  const g = byId.get(m.id);
  if (!g) throw new Error(`space image ${m.id} missing from generated metadata; run scripts/images/build_images.mjs`);
  return { ...m, width: g.width, height: g.height, files: g.files };
});

export const HERO_IMAGE_ID = "nasa-black-hole-jet";

export function spaceImage(id: string): SpaceImageMeta {
  const m = SPACE_IMAGES.find((x) => x.id === id);
  if (!m) throw new Error(`unknown space image ${id}`);
  return m;
}

export function srcSet(m: SpaceImageMeta, fmt: "avif" | "webp"): string {
  return m.files.filter((f) => f.fmt === fmt).map((f) => `/space/${f.name} ${f.w}w`).join(", ");
}

/** Largest file of a format, for the fallback <img src>. */
export function largest(m: SpaceImageMeta, fmt: "avif" | "webp"): SpaceFile {
  return m.files.filter((f) => f.fmt === fmt).sort((a, b) => b.w - a.w)[0];
}
