// Deterministic sigil glyph generator (phi geometry). Usage: node scripts/gen_sigils.mjs
// Reads sigil families + lexicon codewords from the kernel CORE.md ONLY as seeds; writes glyphs
// under public/sigils/<codename>.svg and lib/sigilSet.ts. Keys, families and meanings are never
// written to the output: glyph + neutral codename only (SIGILS EVERYWHERE, MEANINGS NOWHERE).
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const CORE = process.env.KERNEL_CORE || path.join(os.homedir(), "klinge-kernel", "CORE.md");
const PHI = (1 + Math.sqrt(5)) / 2;
const GOLDEN_ANGLE = 2 * Math.PI * (1 - 1 / PHI);
const NAMES = ["Vesper","Halcyon","Umbra","Corvid","Lumen","Argent","Sable","Ember","Tessel","Orrery","Nimbus","Cinder",
  "Meridian","Solace","Quill","Vantage","Ostra","Pallas","Rune","Zephyr","Auric","Borealis","Caldera","Dusk","Eidolon",
  "Fathom","Gossamer","Helix","Iris","Juno","Kestrel","Lyra","Mirage","Nocturne","Onyx","Paragon","Quasar","Riven",
  "Sylph","Talon","Ultima","Verge","Wraith","Xenon","Yonder","Zenith","Aegis","Bastion","Cipher","Draco","Echo",
  "Flint","Garnet","Harbor","Ingot","Jasper","Kindle","Lodestar","Mantle","Nadir","Obsidian","Prism","Rook","Stygian"];

function parseKeys(src) {
  const fam = new Set();
  for (const l of src.split("\n")) { const m = l.match(/^([A-Z]+)\d+\s/); if (m) fam.add(m[1]); }
  const words = [];
  const lex = src.split("\n").find((l) => l.startsWith("LEX NUKE") || /^LEX [A-Z]/.test(l));
  if (lex) for (const part of lex.replace(/\. Full table.*$/, "").split("·")) {
    const w = part.trim().replace(/^LEX\s+/, "").split(/[\s(<]/)[0].replace(/[^A-Z]/g, "");
    if (w.length > 1) words.push(w);
  }
  return [...fam, ...words.map((w) => "LEX:" + w)];
}
function fnv(s) { let h = 2166136261; for (const c of s) { h ^= c.charCodeAt(0); h = Math.imul(h, 16777619); } return h >>> 0; }
function rng(seed) { let a = seed; return () => { a |= 0; a = (a + 0x6d2b79f5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }
const f = (n) => (Math.round(n * 100) / 100).toString();

function glyph(key) {
  const r = rng(fnv(key));
  const C = 50, R = 44, sw = 1.6, el = [];
  const rings = 2 + Math.floor(r() * 3);
  for (let i = 0; i < rings; i++) el.push(`<circle cx="${C}" cy="${C}" r="${f(R / PHI ** i)}"/>`);
  const rot = Math.floor(r() * 360);
  const w = R * 1.2, h = w / PHI; // golden rectangle
  el.push(`<rect x="${f(C - w / 2)}" y="${f(C - h / 2)}" width="${f(w)}" height="${f(h)}" transform="rotate(${rot} ${C} ${C})"/>`);
  if (r() > 0.5) el.push(`<rect x="${f(C - h / 2)}" y="${f(C - w / 2)}" width="${f(h)}" height="${f(w)}" transform="rotate(${rot + 36} ${C} ${C})"/>`);
  // golden-angle constellation
  const n = 5 + Math.floor(r() * 9), off = r() * Math.PI * 2, pts = [];
  for (let i = 1; i <= n; i++) { const rad = R * Math.sqrt(i / n) * 0.9; const a = off + i * GOLDEN_ANGLE; pts.push([C + rad * Math.cos(a), C + rad * Math.sin(a)]); }
  el.push(`<path d="M${pts.map((p) => f(p[0]) + " " + f(p[1])).join("L")}" fill="none" opacity=".55"/>`);
  for (const p of pts) el.push(`<circle cx="${f(p[0])}" cy="${f(p[1])}" r="${f(1.1 + r() * 1.3)}" fill="currentColor" stroke="none"/>`);
  // braid: two phi-phased sines crossing through the centre
  const amp = R / (PHI * 2), a2 = [], b2 = [];
  for (let i = 0; i <= 24; i++) { const x = C - R * 0.85 + (i / 24) * R * 1.7, ph = (i / 24) * Math.PI * 2 * PHI; a2.push(f(x) + " " + f(C + amp * Math.sin(ph))); b2.push(f(x) + " " + f(C - amp * Math.sin(ph))); }
  el.push(`<g transform="rotate(${Math.floor(r() * 180)} ${C} ${C})" opacity=".8"><path d="M${a2.join("L")}" fill="none"/><path d="M${b2.join("L")}" fill="none"/></g>`);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="${sw}" stroke-linecap="round" stroke-linejoin="round">${el.join("")}</svg>\n`;
}

const keys = parseKeys(fs.readFileSync(CORE, "utf8"));
if (keys.length < 20) { console.error("FAIL too few sigil keys parsed: " + keys.length); process.exit(1); }
const used = new Set(), names = [];
for (const k of keys) {
  let i = fnv("name:" + k) % NAMES.length; while (used.has(i)) i = (i + 1) % NAMES.length; used.add(i);
  const code = NAMES[i]; names.push(code);
  fs.writeFileSync(path.join(ROOT, "public", "sigils", code.toLowerCase() + ".svg"), glyph(k));
}
// codename order is shuffled by hash, so index never reveals family order
names.sort((a, b) => fnv(a) - fnv(b));
fs.writeFileSync(path.join(ROOT, "lib", "sigilSet.ts"),
  `// GENERATED by scripts/gen_sigils.mjs. Glyph codenames only; no meanings.\nexport const SIGIL_NAMES = ${JSON.stringify(names)} as const;\nexport type SigilName = (typeof SIGIL_NAMES)[number];\n`);
console.log(`generated ${names.length} sigils`);
