// Internal-link map over the static export: who links to whom. Writes docs/INTERNAL_LINKS.md and
// exits 1 when an indexable page has no inbound internal link (an orphan search engines can only find via the sitemap).
import fs from "node:fs";
import path from "node:path";
import { walk, routeOf, inspect } from "./seo_audit.mjs";

export function linkMap(out) {
  const pages = new Map();
  for (const f of walk(out)) {
    const html = fs.readFileSync(f, "utf8");
    const route = routeOf(out, f);
    const hrefs = new Set();
    for (const m of html.matchAll(/<a\b[^>]*?\bhref="([^"]+)"/g)) {
      let h = m[1].split("#")[0].split("?")[0];
      if (!h.startsWith("/") || h.startsWith("//")) continue;
      h = h.replace(/\/$/, "") || "/";
      if (h !== route) hrefs.add(h);
    }
    pages.set(route, { out: hrefs, noindex: inspect(html).noindex });
  }
  const inbound = new Map([...pages.keys()].map((r) => [r, new Set()]));
  const broken = [];
  for (const [r, p] of pages) {
    for (const h of p.out) {
      if (inbound.has(h)) inbound.get(h).add(r);
      else if (!/\.[a-z0-9]+$/i.test(h) && !h.startsWith("/_next")) broken.push([r, h]);
    }
  }
  const orphans = [...pages].filter(([r, p]) => !p.noindex && r !== "/" && inbound.get(r).size === 0).map(([r]) => r);
  return { pages, inbound, orphans, broken };
}

if (process.argv[1] && process.argv[1].endsWith("link_map.mjs")) {
  const out = process.argv[2] || "out";
  const { pages, inbound, orphans, broken } = linkMap(out);
  const rows = [...pages].filter(([, p]) => !p.noindex).map(([r, p]) => ({ r, o: p.out.size, i: inbound.get(r).size })).sort((a, b) => b.i - a.i || a.r.localeCompare(b.r));
  const md = [
    "# Internal link map",
    "",
    "Generated by `node scripts/link_map.mjs out` after a build. Do not edit by hand.",
    "",
    `Indexable pages: ${rows.length}. Orphans (no inbound internal link): ${orphans.length}. Links to a route that does not exist: ${broken.length}.`,
    "",
    "| Page | Inbound | Outbound |",
    "|---|---:|---:|",
    ...rows.map((x) => `| ${x.r} | ${x.i} | ${x.o} |`),
    "",
    "## Orphans",
    "",
    ...(orphans.length ? orphans.map((o) => `- ${o}`) : ["none"]),
    "",
    "## Broken internal links",
    "",
    ...(broken.length ? broken.map(([a, b]) => `- ${a} -> ${b}`) : ["none"]),
    "",
  ].join("\n");
  fs.mkdirSync("docs", { recursive: true });
  fs.writeFileSync(path.join("docs", "INTERNAL_LINKS.md"), md);
  console.log(`link map: ${rows.length} pages, ${orphans.length} orphans, ${broken.length} broken`);
  for (const o of orphans.slice(0, 40)) console.log("orphan:", o);
  for (const [a, b] of broken.slice(0, 20)) console.log("broken:", a, "->", b);
  process.exit(orphans.length || broken.length ? 1 : 0);
}
